[2024-05-31T08:29:56.393+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T08:29:56.416+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-31T08:29:54.796887+00:00 [queued]>
[2024-05-31T08:29:56.426+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-31T08:29:54.796887+00:00 [queued]>
[2024-05-31T08:29:56.427+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-31T08:29:56.441+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task_start> on 2024-05-31 08:29:54.796887+00:00
[2024-05-31T08:29:56.449+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=727) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T08:29:56.451+0000] {standard_task_runner.py:63} INFO - Started process 729 to run task
[2024-05-31T08:29:56.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'bash_task_start', 'manual__2024-05-31T08:29:54.796887+00:00', '--job-id', '562', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpnn2_avc4']
[2024-05-31T08:29:56.453+0000] {standard_task_runner.py:91} INFO - Job 562: Subtask bash_task_start
[2024-05-31T08:29:56.505+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.bash_task_start manual__2024-05-31T08:29:54.796887+00:00 [running]> on host 29c09f03cc50
[2024-05-31T08:29:56.618+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='bash_task_start' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T08:29:54.796887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T08:29:54.796887+00:00'
[2024-05-31T08:29:56.620+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T08:29:56.634+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-31T08:29:56.635+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Here is your bash message at the start pf your DAG, your workflow has started !"']
[2024-05-31T08:29:56.646+0000] {subprocess.py:86} INFO - Output:
[2024-05-31T08:29:56.648+0000] {subprocess.py:93} INFO - Here is your bash message at the start pf your DAG, your workflow has started !
[2024-05-31T08:29:56.648+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-31T08:29:56.649+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T08:29:56.673+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=stored_procedures, task_id=bash_task_start, execution_date=20240531T082954, start_date=20240531T082956, end_date=20240531T082956
[2024-05-31T08:29:56.707+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T08:29:56.736+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T08:29:56.739+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
