[2024-05-29T08:57:18.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T08:57:18.958+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-29T08:57:16.804132+00:00 [queued]>
[2024-05-29T08:57:18.963+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-29T08:57:16.804132+00:00 [queued]>
[2024-05-29T08:57:18.964+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-29T08:57:18.974+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task_start> on 2024-05-29 08:57:16.804132+00:00
[2024-05-29T08:57:18.981+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2833) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T08:57:18.982+0000] {standard_task_runner.py:63} INFO - Started process 2835 to run task
[2024-05-29T08:57:18.982+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'bash_task_start', 'manual__2024-05-29T08:57:16.804132+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpezfikq5i']
[2024-05-29T08:57:18.984+0000] {standard_task_runner.py:91} INFO - Job 191: Subtask bash_task_start
[2024-05-29T08:57:19.026+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.bash_task_start manual__2024-05-29T08:57:16.804132+00:00 [running]> on host 29c09f03cc50
[2024-05-29T08:57:19.099+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='bash_task_start' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T08:57:16.804132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T08:57:16.804132+00:00'
[2024-05-29T08:57:19.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T08:57:19.112+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-29T08:57:19.113+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Here is your bash message at the start pf your DAG, your workflow has started !"']
[2024-05-29T08:57:19.123+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T08:57:19.127+0000] {subprocess.py:93} INFO - Here is your bash message at the start pf your DAG, your workflow has started !
[2024-05-29T08:57:19.128+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-29T08:57:19.129+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T08:57:19.152+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=stored_procedures, task_id=bash_task_start, execution_date=20240529T085716, start_date=20240529T085718, end_date=20240529T085719
[2024-05-29T08:57:19.197+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T08:57:19.219+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T08:57:19.222+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
